dist: xenial

branches:
  except:
    - /experimental-.*/

language: java

jdk:
  - openjdk8
  - openjdk11

env:
  # NIO + No SSL
  - TRANSPORT=NIO SSL=NO  LOG_LEVEL=OFF
  # NIO + JDK SSL
  - TRANSPORT=NIO SSL=JDK
  # NIO + OpenSSL
  - TRANSPORT=NIO SSL=OPEN_SSL
  # Epoll + No SSL
  - TRANSPORT=EPOLL SSL=NO  LOG_LEVEL=WARN
  # Epoll + JDK SSL
  - TRANSPORT=EPOLL SSL=JDK
  # Epoll + OpenSSL
  - TRANSPORT=EPOLL SSL=OPEN_SSL

services:
  - docker

cache:
  directories:
    - $HOME/.m2

install: true

before_install:
  - 'chmod +x mvnw'
  - 'docker-compose up -d'

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script:
        - 'rm -rf $HOME/.m2/repository/io/hekate'
        - './mvnw clean install -B -DskipTests=true'

script: './mvnw test -pl \!hekate-all -B'

after_success: 'bash <(curl -s https://codecov.io/bash)'

notifications:
  slack: hekate-io:tSiGS0Suj7vrmJN0tlTXw9xn
