dist: xenial

branches:
  except:
  - /experimental-.*/

language: java

jdk:
  - openjdk8
  - openjdk11

env:
  # NIO + No SSL
  - NIO_ENABLED=true   EPOLL_ENABLED=false  NO_SSL_ENABLED=true   SSL_JDK_ENABLED=false  SSL_OPENSSL_ENABLED=false  LOG_LEVEL=OFF
  # NIO + JDK SSL
  - NIO_ENABLED=true   EPOLL_ENABLED=false  NO_SSL_ENABLED=false  SSL_JDK_ENABLED=true   SSL_OPENSSL_ENABLED=false
  # NIO + OpenSSL
  - NIO_ENABLED=true   EPOLL_ENABLED=false  NO_SSL_ENABLED=false  SSL_JDK_ENABLED=false  SSL_OPENSSL_ENABLED=true
  # Epoll + No SSL
  - NIO_ENABLED=false  EPOLL_ENABLED=true   NO_SSL_ENABLED=true   SSL_JDK_ENABLED=false  SSL_OPENSSL_ENABLED=false  LOG_LEVEL=WARN
  # Epoll + JDK SSL
  - NIO_ENABLED=false  EPOLL_ENABLED=true   NO_SSL_ENABLED=false  SSL_JDK_ENABLED=true   SSL_OPENSSL_ENABLED=false
  # Epoll + OpenSSL
  - NIO_ENABLED=false  EPOLL_ENABLED=true   NO_SSL_ENABLED=false  SSL_JDK_ENABLED=false  SSL_OPENSSL_ENABLED=true

services:
  - docker

cache:
  directories:
    - $HOME/.m2

install: true

before_install:
  - 'chmod +x mvnw'
  - 'docker-compose up -d'

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script:
        - 'rm -rf $HOME/.m2/repository/io/hekate'
        - './mvnw clean install -B -DskipTests=true'

script: './mvnw test -pl \!hekate-all -B'

after_success: 'bash <(curl -s https://codecov.io/bash)'

notifications:
  slack: hekate-io:tSiGS0Suj7vrmJN0tlTXw9xn
